version: "3.9"
services:
  backend:
    image: todo-back:1.0
    ports:
      - 5000:60917
    build: "./src/back-end/Todo.Api/"
    networks:
      todo_net:
        ipv4_address: "172.29.0.205"
    depends_on:
      - db
  frontend:
    image: todo-front:1.0
    build: "./src/front-end/Todoapp/"
    networks:
      todo_net:
        ipv4_address: "172.29.0.105"
    ports:
      - 3000:80
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    ports: 
      - 1445:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "9e611524-80a0-4a02-9916-0bdfabf8ef89"
    networks:
      todo_net:
        ipv4_address: "172.29.0.69"
      
networks:
  todo_net:
    ipam:
      driver: default
      config:
        - subnet: "172.29.0.0/24"