FROM node:18-alpine3.20 AS build
WORKDIR /app
COPY ./. ./
RUN npm install -S
RUN npm run build --prod

FROM nginx:latest AS production
COPY --from=build /app/dist/todoapp/browser/. /usr/share/nginx/html/
EXPOSE 80